### ISSUE TITLE
Common metadata tag documentation 404s

### ISSUE THREAD

**Issue by johnlawsharrison** [Borewit/music-metadata-browser#106]
Looks like this markdown file documenting common tag mappings was removed recently:
[common_metadata.md](https://github.com/Borewit/music-metadata-browser/blob/master/doc/common_metadata.md)

Yet it's still linked to in the README.

Is this documentation still around somewhere?

**Comment by Borewit** [comment]
Thanks for reporting this issue.

Yes it is, but in another repo: [common metadata](https://github.com/Borewit/music-metadata/blob/master/doc/common_metadata.md)

**Comment by johnlawsharrison** [comment]
Thanks!

**Comment by Borewit** [comment]
Fixed in [v1.6.3](https://github.com/Borewit/music-metadata-browser/releases/tag/v1.6.3)
