### ISSUE TITLE
Parser loading

### ISSUE THREAD

**Issue by icidasset** [Borewit/music-metadata-browser#14]
Hey @Borewit 👋 
I finally got around to testing this package, sorry for the delay! 😄 

I'm a little confused about the parser loading. So normally the parsers are lazy loaded, but how would that work in a browser? It doesn't seem to work for me (ie. I'm getting `Cannot find module './mpeg/index'` in the browser console). So what's the solution here? Copy all the parser files into the my javascript directory? Or manually import all the parsers I need into my bundle and then write a custom `loadParser` function?

Also, would it be possible to have a static browser build that works straight away without a javascript bundler? I'm not using a javascript bundler in version two of [Diffuse](https://github.com/icidasset/diffuse). Totally cool if not.

Thanks! ✌️

**Comment by Borewit** [comment]
Thanks for reviewing @icidasset.

[music-metadata-browser](https://github.com/Borewit/music-metadata-browser/) is derived from the node.js oriented [music-metadata](https://github.com/borewit/music-metadata), using node modules. 

Using node modules for client side as well seems to become more common. However running modules directly in the browser is not straightforward thing. Although browser have now support for [ES6 modules](https://medium.com/ghostcoder/using-es6-modules-in-the-browser-5dce9ca9e911), using a module bundler like [webpack](https://webpack.js.org/) seems to be most common practice.

I am big fan of keeping things simple, so I perfectly understand you just want to simply add the dependency by injecting a single JavaScript file. Problem with prebundling is that all the dependencies [music-metadata-browser](https://github.com/Borewit/music-metadata-browser/) is using can not be smartly combined with overlapping (NPM) dependencies of other dependecies you might have. A module can be flattened into a single script, but not the other way around.

**Comment by icidasset** [comment]
I figured I'd ask because I barely have any other NPM dependencies in v2 (it's primarily written in Elm). Totally makes sense what you're saying though 😉 

**Any thoughts on my parser-loading question?**
Might be useful to add some documentation about this.
I solved it as follows (not sure if this is the way to go about it).

```js
import * as mm from "music-metadata-browser"
import mpeg from "music-metadata/lib/mpeg"

self.musicMetadata = mm
self.musicMetadata.parsers = { mpeg }
self.musicMetadata.parsingOptions = { loadParser }

function loadParser(parser) {
  return Promise.resolve(
    new self.musicMetadata.parsers[parser]
  )
}
```

**Comment by Borewit** [comment]
There are two 'levels' of lazy loading possible, which are :
1. Lazy loading the JavaScript module source code (getting it over the network)
2. Lazy initializing of parser code (the module is read by JavaScript parser)

Via the options you can register a custom loader for the parser.
I added this on WebAmp's request, but they decided not to use it after all, because the parsers are so small, it would not add any value.

I am not to happy with the way I implemented this, I think it would be nicer to override the module loader, returning the module, instead if the `ITokenParser`. That would eliminate the `new` in your code I guess.

I am very impressed you got a working this way, it was not directly the intend of this option.

I am using `require` to lazy load the parser module, I will replace it with import, maybe that will be more browser friendly and solve your problem.

**Comment by Borewit** [comment]
Prevent using require in: [v0.6.6](https://github.com/Borewit/music-metadata-browser/releases/tag/v0.6.6). 
Can you try that one @icidasset without setting `option.loadParser`?

**Comment by icidasset** [comment]
Same thing @Borewit 

---

It's not entirely clear to me what is supposed to happen.
The `v0.6.6` change is still lazy loading, right?
And in my scenario I would need to disable lazy loading.
So that when I bundle my javascript, the parsers are included already.

Did you have a different view on this?
You think I should be doing lazy loading instead?

---

I'm using [Parcel](https://parceljs.org/) as the bundler and I am building with this command:
`parcel build index.js --no-source-maps --no-cache --no-minify`

And with the following code:

```js
import * as musicMetadata from "music-metadata-browser"
import { StreamingHttpTokenReader } from "streaming-http-token-reader"

self.musicMetadata = musicMetadata
self.StreamingHttpTokenReader = StreamingHttpTokenReader
```

Which I then test in the browser using:

```js
const url = "OMITTED"
const reader = new StreamingHttpTokenReader(url)

reader
  .init()
  .then(() => { return musicMetadata.parseFromTokenizer(reader, reader.contentType) })
  .then(console.log)
```

---

PS. I don't mind my current solution.
Just so you know 😉

**Comment by Borewit** [comment]
[ES6 module](https://nodejs.org/api/esm.html#esm_ecmascript_modules) loading is experimental in Node, maybe I should override the loader in music-metadata-browser with ES6.

Can you try to use ES6 dynamic loading in your code, maybe in comination with [guidance](https://parceljs.org/code_splitting.html) of Parcel? You need a function simular to this (which more or less the same as the [original TypeScript code](https://github.com/Borewit/music-metadata/blob/f803ae2a97925bfe3a112eeb9aed8ced2bb40c8e/src/ParserFactory.ts#L127-L138) in music-metadata)

```JavaScript
// parser string like: 'mpeg' | 'apev2' | 'mp4' | 'asf' | 'flac' | 'ogg' | 'aiff' | 'wavpack' | 'riff' | 'musepack'
function async loadParser(parser) {
  const module = await import('music-metadata/lib/' + parser); // or parser + '/index'
  return new module.default();
}
```

**Comment by icidasset** [comment]
Experiment 1 = failed (imports and `const parsers`)
Experiment 2 = success

The dynamic loading works if I manually copy all the parser files from inside `node_modules` to my `dist` output (aka. build) directory. Which is expected 👍as described in the [Parcel docs](https://parceljs.org/code_splitting.html) (ie. each parser is treated as a separate js bundle).

I think I'm going to stick with my original solution, as I prefer non-lazy loading. It doesn't look like Parcel has the ability to transform lazy-loading imports to strict imports.

And yeah, this javascript code isn't in `diffuse`, I'm trying to keep heavy NPM dependencies out of the project. I have a separate git repo for this, nothing in it that I haven't shown you though.

---

Thanks for all the help! ☺️ 
Feel free to close this if you want to.

**Comment by Borewit** [comment]
Lazy loading disabled in [v0.7.0](https://github.com/Borewit/music-metadata-browser/releases/tag/v0.7.0).

If you can let me know if things a working better for you that would be great.

**Comment by alexbcberio** [comment]
Thanks @Borewit for the fast response, updating to v0.7.0 made it work with no changes in code.

Just you to know, the `response.body.cancel()` call on `fetchFromUrl()` function is throwing the next error:
```javascript
Uncaught (in promise) TypeError: Cannot cancel a readable stream that is locked to a reader
    at parseReadableStream.then.res
```
The metadata is returned correctly in spite of the error

**Comment by Borewit** [comment]
Good to know it is working @alexbcberio.

I have seen error on the cancel before.
If it is bothering you, please report it in a new issue.

**Comment by icidasset** [comment]
Thanks @Borewit !
