### ISSUE TITLE
Error "SCRIPT1004: Expected ';'" in i.e. browser's console

### ISSUE THREAD

**Issue by ileose** [Borewit/music-metadata-browser#194]
Hi, there! 

In react framework, I got some problem with i.e. browser..

It throws an error " SCRIPT1004: Expected ';' " and points to where the error occurred.
![capture](https://user-images.githubusercontent.com/8946678/75950988-1c679800-5eee-11ea-958b-e8feb97eb151.PNG)

Any advice would be greatly appreciated.

**Comment by Borewit** [comment]
Hello @ileose,

I don't think this is directly related to [music-metadata-browser](https://github.com/Borewit/music-metadata-browser).

What version of Internet Explorer are you using?
[music-metadata-browser](https://github.com/Borewit/music-metadata-browser) NPM is written in JavaScript version [ES2017 (ES8)](https://en.wikipedia.org/wiki/ECMAScript#ES2017).

WebPack may transpile it to a different version, maybe not. That first line looks like initialization code generated by WebPack. Is the issue gone if you exclude [music-metadata-browser](https://github.com/Borewit/music-metadata-browser)?

**Comment by ileose** [comment]
I'm using i.e 11.
And use 'babel/preset-env' and 'babel/preset-react' to use the latest JavaScript in project.
This issue is gone when I exclude music-metadata-browser..

**Comment by Borewit** [comment]
Using _latest_ and IE11 is bit of contradicting combination. 

You may get it to work if you ensure Babel is transpiling to [ES5](https://en.wikipedia.org/wiki/ECMAScript#5th_Edition).

**Comment by ileose** [comment]
Babel is used to transpile them to ES5 for using latest and i.e 11.
In other packages that I use, Babel works with them well..
Is there anything I can do?

**Comment by Borewit** [comment]
That is weird.

My code is written TypeScript, and transpiled to ES2017 (ES8), should be very consistent..

There are a few things you can do:
- Make sure IE is not running in backward compatibility mode, ensure is is using IE 11 engine.
- As I suggested before, break that 16509 line in multiple lines so you know on what is causing the `SCRIPT1004: Expected ';'` error
- Try enable IE11 poly-fills, maybe this can help you angular/angular-cli#7776
- Did you publish the code somewhere?

**Comment by Borewit** [comment]
Maybe set IE11 as explicit target in Babel: .https://babeljs.io/docs/en/babel-preset-env#targets

**Comment by Borewit** [comment]
Disable esmodules: https://babeljs.io/docs/en/babel-preset-env#targetsesmodules

**Comment by ileose** [comment]
After all, I couldn't find a solution.
Sorry, I think I should change it to something else..

**Comment by olyop** [comment]
I'm getting this issue too on the latest version of `music-metadata-browser`, Chrome, and Firefox.

`Uncaught SyntaxError: Unexpected token ':'`

I get this error in the browser console when using `webpack-dev-server` and when I try build the project using `webpack` and `ts-loader` (no babel).

When looking through the compiled file, the error occurs in the file: `./node_modules/node-libs-browser/node_modules/util/util.js`

I can't seem to find any issues like this to the `util` and `node-libs-browser` projects.

Does anyone have any ideas?
