### ISSUE TITLE
Module Not Found Error assert/assert.js

### ISSUE THREAD

**Issue by ashinzekene** [Borewit/music-metadata-browser#218]
I get this error when I import the project

`Could not find module in path: 'assert/assert.js' relative to '/node_modules/peek-readable/lib/index.js'`

https://codesandbox.io/s/cool-rain-jwecy

**Comment by Borewit** [comment]
What if you import that module?

```npm install assert`

Some default node.js dependencies need to be explicitly included in a browser environment.

**Comment by ashinzekene** [comment]
Same error. I updated the codesandbox

**Comment by Borewit** [comment]
I am very busy at the moment, please be patient.

**Comment by ashinzekene** [comment]
I think the issue only occurs on codesandbox

**Comment by vatsalm30** [comment]
Hey, I have the same error in vscode, did you get it fixed.
