### ISSUE TITLE
Can't get bit rate of .m4a type of file

### ISSUE THREAD

**Issue by CheetoCheeto** [Borewit/music-metadata-browser#24]
Hello，
I just found when I put .m4a type of file  in this https://audio-tag-analyzer.netlify.com/ website,
the result seems like miss some value: Bit-rate, Number of channels.....

I try different files, but it doesn't work

Sorry for my bad English, hope you can understand

**Comment by Borewit** [comment]
I'll have look, it doesn't use the latest libraries neither.

Thanks for your feedback.

**Comment by CheetoCheeto** [comment]
Oh sorry, I forgot to check the version of that page. But I use the ```"music-metadata-browser": "^1.1.1"``` in local, it seems like have the same problems,

thank you for your reply, hope you have a nice day😊

**Comment by Borewit** [comment]
Hmm, looks like I have some work to do. Need to find some free hours.

**Comment by Borewit** [comment]
Fixed in version [v1.2.0](https://github.com/Borewit/music-metadata-browser/releases/tag/v1.2.0)

There may be m4a files which still lack format information, if you find one, please raise a new issue and attach a zipped copy.

**Comment by CheetoCheeto** [comment]
> Fixed in version [v1.2.0](https://github.com/Borewit/music-metadata-browser/releases/tag/v1.2.0)
> 
> There may be m4a files which still lack format information, if you find one, please raise a new issue and attach a zipped copy.

No problem! Thank you very much. By the way, I have tried .m4a yesterday, can get the information correctly.
