### ISSUE TITLE
Question: Faster parsing mp3 if it has ID3 tags with fetchURL

### ISSUE THREAD

**Issue by vinishgeorge** [Borewit/music-metadata-browser#385]
Is it possible to Identify if the mp3 is an ID3 tagging and parse just the required bytes instead of downloading the whole mp3 using fetch url and then parsing it for all tags available ?

**Comment by Borewit** [comment]
The ID3v2 headers appear at the beginning at the file (for this reason), it's predecessor ID3v1 appears at the end of file. TO figure out if that header is present, it requires to read the last 128 bytes of the file.

fetchURL streams the data. So if you want to ensure that there is an ID3v1, it requires to read the entire stream. To understand if the ID3v2 is present, is a different story. I thought [music-metadata](https://github.com/Borewit/music-metadata) does look for an ID3v1 header in case of a stream, if an ID3v2 header is present (which prevents a lot of reading), but I am not sure. I can look into this is, if that is what you are after. 

This module is designed only read actually holding the metadata. The [strtok3](https://github.com/Borewit/strtok3) is kind of adapter that facilitates only reading chunks necessary for retrieving the metadata.
