### ISSUE TITLE
transpiling to es5 with babel

### ISSUE THREAD

**Issue by digcode** [Borewit/music-metadata-browser#405]
I've got error (SCRIPT1028: SCRIPT1028: Expected identifier, string or number) in production build for edge browser. 
It crashes in file-type/core.js _check function with spread operator
I'am using ts-loader -> babel-loader with preset-env and @babel/plugin-proposal-object-rest-spread plugin to transpile down to es5 but it seems it doesn't.
Any suggestions.

**Comment by Borewit** [comment]
No sorry. Maybe check if you can find a [similar project](https://github.com/Borewit/music-metadata-browser/network/dependents).
