### ISSUE TITLE
Uncaught ReferenceError: `Buffer` is not defined

### ISSUE THREAD

**Issue by olyop** [Borewit/music-metadata-browser#417]
I am receiving this error:
![Capture](https://user-images.githubusercontent.com/20178932/104078803-fdefcd00-5273-11eb-8da9-6147a0e40b59.PNG)

I am importing the package like this:
`import { parseBlob } from "music-metadata-browser"`

I am calling the function like this:
`const metadata = await parseBlob(audio)`

I have already checked that I am passing a object of type `File` using `instanceof`.

I am using the latest version of music-metadata and Chrome.

**Comment by Borewit** [comment]
I think you are missing [`buffer`](https://www.npmjs.com/package/buffer) somewhere in your bundler.

**Comment by olyop** [comment]
Ok, I am using webpack so how do I make it include `buffer` as a dependency?

**Comment by Borewit** [comment]
Maybe this article can help you: [How to Polyfill node core modules in webpack 5](https://sanchit3b.medium.com/how-to-polyfill-node-core-modules-in-webpack-5-905c1f5504a0).

**Comment by olyop** [comment]
Thank you, I managed to find a solution. For anyone else looking, [It's an issue with webpack 5](https://github.com/webpack/changelog-v5/issues/10#issuecomment-615877593).

**Comment by n1ru4l** [comment]
For anyone using a modern bundler like `vite` or `snowpack`, you will have to add `yarn add buffer` and create a polyfill file where you assign it the window object.

I was wondering whether this library could instead operate on Uint8Arrays instead of buffers?

**Comment by Borewit** [comment]
> I was wondering whether this library could instead operate on Uint8Arrays instead of buffers?

That's a good question, I have been been working on that behind the screens. One of the issues is that the [TextEncoder](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder) is limited to utf-8 encoding and decoding in the Node.js implementation.

Related to:
- https://github.com/sindresorhus/file-type/issues/437
- https://github.com/Borewit/token-types/issues/245

**Comment by vaishnavsm** [comment]
> For anyone using a modern bundler like `vite` or `snowpack`, you will have to add `yarn add buffer` and create a polyfill file where you assign it the window object.
> 
> ```tsx
> import { Buffer } from "buffer";
> 
> if (typeof window !== "undefined" && typeof Buffer === "undefined") {
>   window.Buffer = Buffer;
> }
> ```

I think you meant `typeof window.Buffer === "undefined"`

Also, if you are using rollup, I've found that you have to install events yourself. The plugins for rollup don't work right now, and they don't seem to be necessary. 

Thanks for the great work! :)

**Comment by Borewit** [comment]
Maybe we can get rid of Buffer Borewit/token-types#650

**Comment by Borewit** [comment]
[music-metadata](https://github.com/Borewit/music-metadata) now offers Node.js free functionality for non Node.js engines.

Polyfilling Buffer or Node.js streams should belong to the past, and it also makes this package obsolete.

But... only available as ECMA Script Module (ESM), CommonJS is no longer supported.

**Comment by olyop** [comment]
Thank you for your work @Borewit

Just tested it out in a project and works great, no Buffer dependency needed

**Comment by Borewit** [comment]
> Thank you for your work @Borewit
> 
> Just tested it out in a project and works great, no Buffer dependency needed

I was a complex and a time consuming architectural change, so glad to hear it worked out for you, thanks for providing that feedback.
