### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by NdaJunior** [Borewit/music-metadata-browser#608]
I get this error 

`Uncaught ReferenceError: exports is not defined`

after importing the module into my javascript file. Anyone else ran into this ?

**Comment by Borewit** [comment]
You will need a module bundler, like [Webpack](https://webpack.js.org/) to work with this CommonJS module in a browser environment.

You can see how [other open source Github project](https://github.com/Borewit/music-metadata-browser/network/dependents) integrated this module.

**Comment by ZMYaro** [comment]
I would like to throw in my agreement I would appreciate if this library supported standard JS module syntax instead of only CommonJS since its purpose is to be used in browser applications.
