### ISSUE TITLE
2.5.0 Version updates Break Some Features on Safari 

### ISSUE THREAD

**Issue by martinfoakes** [Borewit/music-metadata-browser#624]
## Issue:

After updating this package to the latest `2.5.0` version within our team's app, the functionality we had around audio files being uploaded was completely broken on Safari alone. All other browsers were unaffected by the update

Looking at the changelog, looks like the issue might be within the return of the `parseBlob` function:

```js
if (blob instanceof File) {
  fileInfo.path = (blob as File).name;
}

return parseReadableStream(blob.stream(), {.....);
```

That switching of the `blob` from being a `Uint8Array` to a `ReadableStream` comes with an issue with the Default Reader of the `ReadableStream` -> https://developer.mozilla.org/en-US/docs/Web/API/ReadableStreamDefaultReader

Within the `readable-web-to-node-stream` package, the class constructor calls the `ReadableStream.getReader()` method, which returns the `ReadableStreamDefaultReader` that Safari has issues with -> 

https://github.com/Borewit/readable-web-to-node-stream/blob/e81a7c91b1fa73cb11dc50bac41a9f033e0d030e/lib/index.ts#L27

**Comment by Borewit** [comment]
Hi @martinfoakes.

Thanks for your detailed analysis.
 
It was in PR #597 where the switch from `Uint8Array` to a `ReadableStream` has been made. By doing that I hoped that a file uploaded was streamed directly to the parser, rather then entirely buffered first. Also the code became a bit simpler like this.

The [`ReadableStream.getReader()`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/getReader) should be compatible with Safari 10.1. I don't have a Safari browser on my system, so not super easy for me to debug. I am not sure what is the best way forward here.

**Comment by Borewit** [comment]
I have tried to upload a file in Safari 14.1 via [browserstack.com](https://live.browserstack.com/) to [audio-tag-analyzer](https://github.com/Borewit/audio-tag-analyzer), which is using the `parseBlob` function. I did not experience any problem.

**Comment by kawka-maciej** [comment]
the `blob.stream` is available since 14.1 so it works within your tests. But for the older versions, it indeed breaks some functionality as described above:

https://caniuse.com/mdn-api_blob_stream

**Comment by Borewit** [comment]
Please confirm compatibility with older Safari browsers is restored in [v2.5.1](https://github.com/Borewit/music-metadata-browser/releases/tag/v2.5.1).

**Comment by kawka-maciej** [comment]
Works well on Safari `Version 13.1.3 (15609.4.1)`.
