### ISSUE TITLE
aac file duration is negative

### ISSUE THREAD

**Issue by lopaz** [Borewit/music-metadata-browser#70]
music-metadata version: 4.8.0( I use music-metadata-browser@1.6.0, which depends on this version)
music file: https://resources-1257265876.cos.ap-beijing.myqcloud.com/debug/duration-parse-problem.m4a

the parsed duration is -1024. 

metadata parsed:
format:
bitrate: -3387.5546875
codec: "AAC"
codecProfile: "AAC LC"
container: "ADTS/MPEG-4"
duration: -1024
lossless: false
numberOfChannels: 1
numberOfSamples: 1024
sampleRate: -1

**Comment by Borewit** [comment]
> Sorry for not testing before post this issue.

No problem, I appreciate the effort to report your issue.

I downloaded [your sample file](https://resources-1257265876.cos.ap-beijing.myqcloud.com/debug/duration-parse-problem.m4a) and dragged it into [audio-tag-analyzer](https://audio-tag-analyzer.netlify.com/) (which is currently using [music-metadata-browser v1.6.0](https://github.com/Borewit/music-metadata-browser)), seems to extract the duration correct.

![Screenshot from 2019-09-27 10-13-02](https://user-images.githubusercontent.com/23255260/65753537-83974a00-e10f-11e9-8a46-60062209e137.png)

I did not have the opportunity yet to look into you code fragment.

**Comment by lopaz** [comment]
I noticed the 'File Type' on your snapshot image was different from which I used. After some tests, I found out the reason:
I use `mm.parseBuffer(buffer, **"audio/mpeg"**, { duration: true })` for parsing mp3 files, which is correct. When the same code used to parse acc files, the duration would be negative. I checked the docs again, and saw that music-metadata would try to guess the MIME-type when not provided or not understood, so I changed the code to `mm.parseBuffer(buffer, "", { duration: true })`, it worked for both mp3 files and acc files. 
Thanks for your help. @Borewit

**Comment by Borewit** [comment]
Better to use the build File/Blob parser, that will take the right mime-type from the browser.
```js
mm.parseBlob(file, { duration: true }).then(metadata => {});
```

**Comment by hoangmf** [comment]
I think it might return 0 if not using the duration option. 

https://www.mediafire.com/file/tb9e7xnj1kjxdnb/Doja_Cat_-_Say_So_%2528Audio%2529.aac/file

**Comment by microvn** [comment]
I think it might return 0 if not using the duration option. 
https://www.mediafire.com/file/tb9e7xnj1kjxdnb/Doja_Cat_-_Say_So_%2528Audio%2529.aac/file
