### ISSUE TITLE
TypeError: can't access property "call", Stream is undefined

### ISSUE THREAD

**Issue by Zedonboy** [Borewit/music-metadata-browser#755]
I am using vite.

i have added polyfills, but it still gives me this error

**Comment by itxve** [comment]
I'm also using vite, unfortunately an error occurred。
<details>
    <summary> Error</summary>
  _stream_readable.js:184 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at new Readable (_stream_readable.js:184:10)
    at new ReadableWebToNodeStream (index.js:17:9)
    at parseReadableStream (index.js:30:16)
    at Object.parseBlob (index.js:48:12)
    at HTMLInputElement.<anonymous> (UploadSong.vue:20:7)
</details>

**Comment by Borewit** [comment]
Gents, can you provide me with a repo to reproduce the error.

**Comment by itxve** [comment]
> Gents, can you please provide me with a repo to reproduce the error?
I provided an example of an error.
[music-metadata-browser-vite](https://github.com/itxve/music-metadata-browser-vite)

**Comment by Borewit** [comment]
Thanks @itxve, I am very busy at the moment, please give me 2 weeks

**Comment by Borewit** [comment]
I had a look to the repo. To get to the error you describe I had to define `global`, which I did by adding:
```html
<script>window.global = window;</script>
```
to index.html

The basic issue is basically polyfill Node specific dependencies.
To get around the issue you had, can be done by adding [events](https://www.npmjs.com/package/events) as a dependency.

Next one will be Buffer. It is probably fixable as well, but here I stop my little Vite adventure. I know it is painful to get this things right, unfortunately I make it much easier for you. Making this library available for Node.js and browser, without this kind of distracting bureaucracy is unfortunately not possible yet. By all means, please prove me wrong.

**Comment by itxve** [comment]
thank you very much ,I got my demo working with this answer😄。
[ process is not defined ](https://github.com/vitejs/vite/issues/3817#issuecomment-864450199)

first
```
yarn add events
```

in `main.ts`
```
import { Buffer } from "buffer";
import process from "process";
window.Buffer = Buffer;
window.process = process;
```
in `vite.config.ts`
```

// https://vitejs.dev/config/
export default defineConfig({
  define: {
    global: "window",
  },
  plugins: [vue()],
});
```

**Comment by Borewit** [comment]
Thanks for sharing @itxve!

Would you like link in the README to your repo?

**Comment by itxve** [comment]
> Thanks for sharing @itxve!
> 
> Would you like link in the README to your repo?

I Would Be Pleased To.
