### ISSUE TITLE
Add MusicSource to online demos

### ISSUE THREAD

**Issue by tgambet** [Borewit/music-metadata-browser#787]
Hello @Borewit,
This is not an issue, but repository discussions are not enabled so I take the liberty to contact you this way.
I have release an open source project that heavily relies on music-metadata-browser: [MusicSource](https://github.com/tgambet/musicsource).
You might want to take a look. Thank you for your work!

**Comment by Borewit** [comment]
Looks awesome @tgambet! Thanks sharing.

Feel free to create a PR listing your project as part of [Online demo](https://github.com/Borewit/music-metadata-browser#online-demos).
